"use strict";
module.exports = {
    config: {
        theme: "catppuccin-mocha",
        updateChannel: 'stable',
        fontSize: 22,
        fontFamily: 'Geist Mono, "Lucida Console", monospace',
        fontWeight: 'normal',
        fontWeightBold: 'normal',
        lineHeight: 1,
        letterSpacing: 0,
        cursorColor: 'rgba(248,28,229,0.8)',
        cursorAccentColor: '#000',
        cursorShape: 'UNDERLINE',
        cursorBlink: true,
        foregroundColor: '#fff',
        backgroundColor: '#000',
        selectionColor: 'rgba(248,28,229,0.3)',
        borderColor: '#333',
        css: '',
        termCSS: '',
        workingDirectory: 'D:',
        showHamburgerMenu: '',
        showWindowControls: '',
        padding: '12px 14px',
        hyperWindowSize: {
            width: 1300,
            height: 480,
            startX: 70,
            startY: 50
        },
        colors: {
            black: '#000000',
            red: '#C51E14',
            green: '#1DC121',
            yellow: '#C7C329',
            blue: '#0A2FC4',
            magenta: '#C839C5',
            cyan: '#20C5C6',
            white: '#C7C7C7',
            lightBlack: '#686868',
            lightRed: '#FD6F6B',
            lightGreen: '#67F86F',
            lightYellow: '#FFFA72',
            lightBlue: '#6A76FB',
            lightMagenta: '#FD7CFC',
            lightCyan: '#68FDFE',
            lightWhite: '#FFFFFF',
            limeGreen: '#32CD32',
            lightCoral: '#F08080',
        },
        shell: 'D:\\Program Files\\Git\\bin\\bash.exe',
        shellArgs: ['--login', '-i'],
        env: {},
        bell: 'SOUND',
        copyOnSelect: false,
        defaultSSHApp: true,
        quickEdit: false,
        macOptionSelectionMode: 'vertical',
        webGLRenderer: true,
        webLinksActivationKey: '',
        disableLigatures: false,
        disableAutoUpdates: false,
        screenReaderMode: false,
        preserveCWD: true,
    },
    plugins: ["@catppuccin/hyper#1.0.8", "hyper-window-size"],
    localPlugins: [],
    keymaps: {
    },
};